wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
max_epoch:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 12
_wandb:
  desc: null
  value:
    python_version: 3.8.20
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1734786725.0
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.20
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
